<?php
return [
    "Waldo"=> [
        "href"=> "https://en.wikipedia.org/wiki/Waldo_County,_Maine",
        "location"=> "midcoast",
        "img"=> "/res/towns/Belfast,_Maine.jpg",
        "dark"=> false,
        "credit"=> "<a href=\"https://commons.wikimedia.org/w/index.php?curid=47214052\">Centpacrr at en.wikipedia, CC BY-SA 3.0</a>",
        "blurb"=> "Combining a quirky, artistic vibe with deep agricultural roots, Waldo County is home to the seaside city of Belfast. It's a place where organic farms thrive alongside a busy working waterfront, offering a unique blend of coastal and rural life."
    ],
    "Hancock"=> [
        "href"=> "https://en.wikipedia.org/wiki/Hancock_County,_Maine",
        "location"=> "downeast",
        "img"=> "/res/towns/Egg_Rock_Light_-_Frenchman_Bay_ME.jpg",
        "dark"=> true,
        "credit"=> "<a href=\"https://commons.wikimedia.org/w/index.php?curid=10597738\">liz west from Boxborough, MA - Egg Rock lighthouse a, CC BY 2.0</a>",
        "blurb"=> "Boasting Acadia National Park and the popular town of Bar Harbor, Hancock is the jewel of the Maine coast. Its dramatic granite cliffs and scenic harbors draw millions of visitors, while its interior remains a quiet sanctuary of woods and ponds."
    ],
    "Knox"=> [
        "href"=> "https://en.wikipedia.org/wiki/Knox_County,_Maine",
        "location"=> "midcoast",
        "img"=> "/res/towns/Camden_Maine_October_2021_001.jpg",
        "dark"=> false,
        "credit"=> "<a href=\"https://commons.wikimedia.org/w/index.php?curid=111114850\">King of Hearts - Own work, CC BY-SA 4.0</a>",
        "blurb"=> "The \"Windjammer Capital of the World,\" Knox County is defined by its maritime tradition. Rockland and Camden serve as bustling hubs for the lobster industry and fine arts, set against a backdrop of mountains that meet the Atlantic Ocean."
    ],
    "Lincoln"=> [
        "href"=> "https://en.wikipedia.org/wiki/Lincoln_County,_Maine",
        "location"=> "midcoast",
        "img"=> "/res/towns/BoothbayHarbor.jpg",
        "dark"=> false,
        "credit"=> "<a href=\"https://commons.wikimedia.org/w/index.php?curid=128449201\">Whitehouse27 - Own work, CC BY-SA 4.0</a>",
        "blurb"=> "Characterized by long, narrow peninsulas and historic villages like Wiscasset and Damariscotta, Lincoln County is quintessential coastal Maine. It's a haven for oyster lovers, antique hunters, and those seeking a slower pace of life by the water."
    ],
    "Androscoggin"=> [
        "href"=> "https://en.wikipedia.org/wiki/Androscoggin_County,_Maine",
        "location"=> "southern",
        "img"=> "/res/towns/Lewiston_Hathorn_Hall_by_Odwallah-cc-by-sa-4.0.jpg",
        "dark"=> false,
        "credit"=> "<a href=\"https://commons.wikimedia.org/w/index.php?curid=47428915\">Odwallah - Own work, CC BY-SA 4.0</a>",
        "blurb"=> "Centered on the Twin Cities of Lewiston and Auburn, this county is defined by its industrial heritage and the river that shares its name. It's a hub for manufacturing and services, blending urban grit with beautiful rural landscapes in the surrounding hills.",
        "include" => false,
    ],
    "Aroostook"=> [
        "href"=> "https://en.wikipedia.org/wiki/Aroostook_County,_Maine",
        "location"=> "northern",
        "img"=> "/res/towns/buttermilk-falls-pexels-bel-tm-2150970896-34652617.jpg",
        "dark"=> true,
        "credit"=> "Photo by <a href='https://www.pexels.com/photo/stunning-buttermilk-falls-in-autumn-maine-forest-34652617/'>Bel TM</a>",
        "blurb"=> "Known simply as \"The County,\" this is Maine's northernmost and largest region. It's famous for vast potato fields, Acadian culture, and endless forests. It's a place where the scale of the landscape is matched only by the legendary hospitality of the locals.",
        "include" => false,
    ],
    "Cumberland"=> [
        "href"=> "https://en.wikipedia.org/wiki/Cumberland_County,_Maine",
        "location"=> "southern",
        "img"=> "/res/towns/portland-maine-lighthouse-pexels-sumeeta-chaudhri-10235859-6143735.jpg",
        "dark"=> true,
        "credit"=> "<a href=\"https://www.pexels.com/photo/lighthouse-tower-on-rocky-coast-6143735/\">Photo by Sumeeta Chaudhri</a>",
        "blurb"=> "The state's most populous county is home to Portland, Maine's cultural and economic heart. It offers a sophisticated mix of world-class dining, historic architecture, and a stunning coastline, making it the primary gateway for visitors and commerce alike.",
        "include" => false,
    ],
    "Franklin"=> [
        "href"=> "https://en.wikipedia.org/wiki/Franklin_County,_Maine",
        "location"=> "western",
        "img"=> "/res/towns/Franklin_County_Courthouse_Farmington_5.jfif",
        "dark"=> false,
        "credit"=> "<a href=\"https://commons.wikimedia.org/w/index.php?curid=29239052\">Jon Platek - Own work, CC BY-SA 3.0</a>",
        "blurb"=> "A paradise for outdoor enthusiasts, Franklin is home to the western mountains and major ski resorts like Sugarloaf. Between the rugged peaks and the expansive lakes, it's a premier destination for hiking, skiing, and soaking in Maine's wilder side.",
        "include" => false,
    ],
    "Kennebec"=> [
        "href"=> "https://en.wikipedia.org/wiki/Kennebec_County,_Maine",
        "location"=> "central",
        "img"=> "/res/towns/Maine_State_House_exterior_view-quinton-solviev.jpg",
        "dark"=> false,
        "credit"=> "<a href='https://commons.wikimedia.org/w/index.php?curid=168967742'>Quintin Soloviev - Own work, CC BY 4.0</a>",
        "blurb"=> "As the seat of state government in Augusta, Kennebec County is the political center of Maine. Beyond the capital, you'll find the charming Belgrade Lakes region, offering a classic Maine experience of summer cottages and tranquil water.",
        "include" => false,
    ],
    "Oxford"=> [
        "href"=> "https://en.wikipedia.org/wiki/Oxford_County,_Maine",
        "location"=> "western",
        "img"=> "/res/towns/Spruce_Mountain_in_Fall.jpg",
        "dark"=> false,
        "credit"=> "<a href=\"https://commons.wikimedia.org/w/index.php?curid=83370141\">Wolfpoint - Own work, CC BY-SA 4.0</a>",
        "blurb"=> "Stretching along the New Hampshire border, Oxford County is a land of mountains and minerals. From the ski slopes of Sunday River to the gem mines of the western hills, it provides some of the most rugged and beautiful terrain in New England.",
        "include" => false,
    ],
    "Penobscot"=> [
        "href"=> "https://en.wikipedia.org/wiki/Penobscot_County,_Maine",
        "location"=> "central",
        "img"=> "/res/towns/Bangor,_Maine.jpg",
        "dark"=> false,
        "credit"=> "<a href=\"https://commons.wikimedia.org/w/index.php?curid=175161516\">Quintin Soloviev - Own work, CC BY 4.0</a>",
        "blurb"=> "Anchored by Bangor, this county serves as the commercial hub for central and northern Maine. It's steeped in lumber history and is home to the University of Maine in Orono, balancing a busy urban center with vast stretches of timberland.",
        "include" => false,
    ],
    "Piscataquis"=> [
        "href"=> "https://en.wikipedia.org/wiki/Piscataquis_County,_Maine",
        "location"=> "central",
        "img"=> "/res/towns/DoverFoxcroftME_WoolenMill_2.jpg",
        "dark"=> false,
        "credit"=> "<a href=\"https://commons.wikimedia.org/w/index.php?curid=42751401\">Magicpiano - Own work, CC BY-SA 3.0</a>",
        "blurb"=> "Maine's least populous county is a true wilderness frontier. It contains the majestic Mount Katahdin, the northern terminus of the Appalachian Trail, and the massive Moosehead Lake, offering unparalleled opportunities for remote adventure.",
        "include" => false,
    ],
    "Sagadahoc"=> [
        "href"=> "https://en.wikipedia.org/wiki/Sagadahoc_County,_Maine",
        "location"=> "southern",
        "img"=> "/res/towns/Doubling_Point_Light_with_Bath_Iron_Works.jfif",
        "dark"=> false,
        "credit"=> "<a href=\"https://commons.wikimedia.org/w/index.php?curid=7617270\">Jameslwoodward - Own work, CC BY-SA 3.0</a>",
        "blurb"=> "Despite being the state's smallest county by land area, Sagadahoc packs a punch with its rich shipbuilding history in Bath. Its coastal reaches include the stunning Popham Beach and several picturesque points reaching into the Gulf of Maine.",
        "include" => false,
    ],
    "Somerset"=> [
        "href"=> "https://en.wikipedia.org/wiki/Somerset_County,_Maine",
        "location"=> "western",
        "img"=> "/res/towns/S_Branch_Carrabassett_R_at_AT_crossing.jpg",
        "dark"=> false,
        "credit"=> "<a href=\"https://commons.wikimedia.org/w/index.php?curid=4071599\">petersent - Self-photographed, Public Domain</a>",
        "blurb"=> "Stretching from the Fairfield farmlands to the Canadian border, Somerset is a giant of the Maine woods. It's the top maple syrup producer in the state and a prime destination for whitewater rafting on the Kennebec and Dead Rivers.",
        "include" => false,
    ],
    "Washington"=> [
        "href"=> "https://en.wikipedia.org/wiki/Washington_County,_Maine",
        "location"=> "eastern",
        "img"=> "/res/towns/pexels-nicole-seidl-35046780.jpg",
        "dark"=> false,
        "credit"=> "<a href=\"https://www.pexels.com/photo/quoddy-head-lighthouse-in-coastal-maine-35046780/\">Photo by Nicole Seidl</a>",
        "blurb"=> "Often called the \"Sunrise County,\" this is the easternmost point of the U.S. It's a rugged, salt-of-the-earth region known for wild blueberries, dramatic tides in the Bay of Fundy, and a coastline that remains beautifully undeveloped.",
        "include" => false,
    ],
    "York"=> [
        "href"=> "https://en.wikipedia.org/wiki/York_County,_Maine",
        "location"=> "southern",
        "img"=> "/res/towns/Biddeford_City_Hall_2020.jpg",
        "dark"=> false,
        "credit"=> "<a href=\"https://commons.wikimedia.org/w/index.php?curid=93230628\">City of Biddeford - Own work, CC BY-SA 4.0</a>",
        "blurb"=> "As Maine's oldest county and southern gateway, York is famous for its sandy beaches and historic coastal towns like York and Kennebunkport. It bridges the gap between the bustle of the Boston corridor and the distinct \"Vacationland\" feel of Maine.",
        "include" => false,
    ]
];